### ISSUE TITLE
clientside js offline mode 

### ISSUE THREAD

**Issue by 100ideas** [textileio/js-todo-demo#1]
it would be super awesome if this demo app could demonstrate how to work in offline mode, where "offline mode" means unable to connect to thread service or daemon (either on local host or via network). i.e. app maintains state & thread updates clientside (indexdb?) & synchronizes with remote threads if possible.

This depends on the implementation for `Internal Event Store for Textile's Threads Protocol` being added to `@textile/threads` npm package. For now see changes in WIP branch https://github.com/textileio/js-threads/compare/carson/store-initial

**Comment by carsonfarmer** [comment]
This is now possible with https://github.com/textileio/js-threads!

**Comment by carsonfarmer** [comment]
We haven't yet moved this example over to that offline first mode, but it is now possible.

**Comment by vasa-develop** [comment]
@carsonfarmer Does this mean that we can sync 2 or more thread peers without using a remote `go-threads` daemon or does it sync with other thread peers after it eventually connects to a remote `go-threads` daemon?

**Comment by carsonfarmer** [comment]
At the moment, it still requires connecting to a local/remote go-threads daemon for networking.

**Comment by carsonfarmer** [comment]
Closing this in favor of discussions on https://github.com/textileio/js-threads
