### ISSUE TITLE
Does not build

### ISSUE THREAD

**Issue by philholden** [textileio/js-todo-demo#9]
```
yarn build
yarn run v1.22.4
warning ../../package.json: No license field
$ react-scripts build
Creating an optimized production build...
Failed to compile.

./node_modules/@textile/threads-client/dist/src/index.js
Cannot find module: '@textile/threads-client-grpc/api_pb_service'. Make sure this package is installed.

You can install this package by running: yarn add @textile/threads-client-grpc/api_pb_service.
```

**Comment by carsonfarmer** [comment]
My apologies @philholden, this repo is pretty outdated, and we've moved our examples over to Closing this in favor of discussions on https://github.com/textileio/js-examples. Please take a look at some of the demos there. I'm going to archive this one to avoid confusion in the future.

**Comment by carsonfarmer** [comment]
But just to answer your question, it looks like maybe you needed to run `yarn install` first before running the build script?
